version: '3.8'
services:
  pgdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
      - 5432:5432 
    volumes:
      - .dbdata:/var/lib/postgresql

  bot1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "bots.py"]
             
  bot2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "consumer.py"]



  
  
   